# Generated by Django 4.2 on 2025-10-28 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marcas', '0001_initial'),
        ('proveedores', '0003_alter_proveedor_cuit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoaccess', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('minimo', models.IntegerField(blank=True, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('grupo', models.IntegerField(blank=True, null=True)),
                ('pventa1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pventa2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pventa3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pventa4', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comib', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comiu', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('codigobarra', models.CharField(max_length=250)),
                ('pmoneda', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cotizacion', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pcompra', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ocultar', models.BooleanField(default=False)),
                ('margen1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('margen2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('margen3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('margen4', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('d1', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('d2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('d3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('flete', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fechaprecio', models.DateTimeField()),
                ('codigoproducto', models.CharField(blank=True, max_length=250, null=True)),
                ('selecciones', models.BooleanField(default=False)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marcas.marca')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
    ]
