# Generated by Django 4.2 on 2025-10-29 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'verbose_name_plural': 'Articulos'},
        ),
    ]
