# Generated by Django 4.2 on 2025-10-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='codigobarra',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='ocultar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='selecciones',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
