# Generated by Django 4.2 on 2025-10-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_alter_articulo_codigobarra_alter_articulo_ocultar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fechaprecio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
