# Generated by Django 4.2 on 2025-10-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_alter_articulo_fechaprecio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
