# Generated by Django 4.2 on 2025-10-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('codigoaccess', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Marcas',
            },
        ),
    ]
