# Generated by Django 4.2 on 2025-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoaccess', models.IntegerField()),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('domicilio', models.CharField(blank=True, max_length=150, null=True)),
                ('localidad', models.CharField(blank=True, max_length=150, null=True)),
                ('codpostal', models.CharField(blank=True, max_length=50, null=True)),
                ('cuit', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=150, null=True)),
                ('pais', models.CharField(blank=True, max_length=150, null=True)),
                ('observacion', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
